# Generated by Django 5.1.2 on 2024-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_visibility_companyinvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('admin', 'Admin')], default='member', max_length=10),
        ),
    ]
