# Generated by Django 5.1.2 on 2024-11-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyinvitation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='visibility',
            field=models.CharField(choices=[('hidden', 'Hidden'), ('visible', 'Visible')], default='visible', max_length=7),
        ),
        migrations.AlterField(
            model_name='companyinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
